<?php

declare(strict_types=1);

namespace Rdcstarr\Locale\Database\Seeders;

use Illuminate\Database\Seeder;
use Rdcstarr\Locale\Models\Country;
use Rdcstarr\Locale\Models\Language;

final class CountriesSeeder extends Seeder
{
    /**
     * Seed the countries table with ISO 3166-1 country data.
     * Requires LanguagesSeeder to have run first (resolves primary_language_id).
     *
     * @return void
     */
    public function run(): void
    {
        $languageIds  = Language::pluck('id', 'code');
        $callingCodes = require __DIR__ . '/../data/calling-codes.php';

        $countries = [
            // ── Europe ──────────────────────────────────────────────────────
            [
                'name'                 => 'Andorra',
                'code'                 => 'AD',
                'flag'                 => 'ad',
                'flag_emoji'           => '🇦🇩',
                'timezone'             => 'Europe/Andorra',
                'primary_language_code' => 'es',
            ],
            [
                'name'                 => 'Albania',
                'code'                 => 'AL',
                'flag'                 => 'al',
                'flag_emoji'           => '🇦🇱',
                'timezone'             => 'Europe/Tirane',
                'primary_language_code' => 'en',
            ],
            [
                'name'                 => 'Austria',
                'code'                 => 'AT',
                'flag'                 => 'at',
                'flag_emoji'           => '🇦🇹',
                'timezone'             => 'Europe/Vienna',
                'primary_language_code' => 'de',
            ],
            [
                'name'                 => 'Bosnia and Herzegovina',
                'code'                 => 'BA',
                'flag'                 => 'ba',
                'flag_emoji'           => '🇧🇦',
                'timezone'             => 'Europe/Sarajevo',
                'primary_language_code' => 'sr',
            ],
            [
                'name'                 => 'Belgium',
                'code'                 => 'BE',
                'flag'                 => 'be',
                'flag_emoji'           => '🇧🇪',
                'timezone'             => 'Europe/Brussels',
                'primary_language_code' => 'fr',
            ],
            [
                'name'                 => 'Bulgaria',
                'code'                 => 'BG',
                'flag'                 => 'bg',
                'flag_emoji'           => '🇧🇬',
                'timezone'             => 'Europe/Sofia',
                'primary_language_code' => 'bg',
            ],
            [
                'name'                 => 'Belarus',
                'code'                 => 'BY',
                'flag'                 => 'by',
                'flag_emoji'           => '🇧🇾',
                'timezone'             => 'Europe/Minsk',
                'primary_language_code' => 'ru',
            ],
            [
                'name'                 => 'Switzerland',
                'code'                 => 'CH',
                'flag'                 => 'ch',
                'flag_emoji'           => '🇨🇭',
                'timezone'             => 'Europe/Zurich',
                'primary_language_code' => 'de',
            ],
            [
                'name'                 => 'Cyprus',
                'code'                 => 'CY',
                'flag'                 => 'cy',
                'flag_emoji'           => '🇨🇾',
                'timezone'             => 'Asia/Nicosia',
                'primary_language_code' => 'el',
            ],
            [
                'name'                 => 'Czech Republic',
                'code'                 => 'CZ',
                'flag'                 => 'cz',
                'flag_emoji'           => '🇨🇿',
                'timezone'             => 'Europe/Prague',
                'primary_language_code' => 'cs',
            ],
            [
                'name'                 => 'Germany',
                'code'                 => 'DE',
                'flag'                 => 'de',
                'flag_emoji'           => '🇩🇪',
                'timezone'             => 'Europe/Berlin',
                'primary_language_code' => 'de',
            ],
            [
                'name'                 => 'Denmark',
                'code'                 => 'DK',
                'flag'                 => 'dk',
                'flag_emoji'           => '🇩🇰',
                'timezone'             => 'Europe/Copenhagen',
                'primary_language_code' => 'da',
            ],
            [
                'name'                 => 'Estonia',
                'code'                 => 'EE',
                'flag'                 => 'ee',
                'flag_emoji'           => '🇪🇪',
                'timezone'             => 'Europe/Tallinn',
                'primary_language_code' => 'en',
            ],
            [
                'name'                 => 'Spain',
                'code'                 => 'ES',
                'flag'                 => 'es',
                'flag_emoji'           => '🇪🇸',
                'timezone'             => 'Europe/Madrid',
                'primary_language_code' => 'es',
            ],
            [
                'name'                 => 'Finland',
                'code'                 => 'FI',
                'flag'                 => 'fi',
                'flag_emoji'           => '🇫🇮',
                'timezone'             => 'Europe/Helsinki',
                'primary_language_code' => 'fi',
            ],
            [
                'name'                 => 'France',
                'code'                 => 'FR',
                'flag'                 => 'fr',
                'flag_emoji'           => '🇫🇷',
                'timezone'             => 'Europe/Paris',
                'primary_language_code' => 'fr',
            ],
            [
                'name'                 => 'United Kingdom',
                'code'                 => 'GB',
                'flag'                 => 'gb',
                'flag_emoji'           => '🇬🇧',
                'timezone'             => 'Europe/London',
                'primary_language_code' => 'en',
            ],
            [
                'name'                 => 'Greece',
                'code'                 => 'GR',
                'flag'                 => 'gr',
                'flag_emoji'           => '🇬🇷',
                'timezone'             => 'Europe/Athens',
                'primary_language_code' => 'el',
            ],
            [
                'name'                 => 'Croatia',
                'code'                 => 'HR',
                'flag'                 => 'hr',
                'flag_emoji'           => '🇭🇷',
                'timezone'             => 'Europe/Zagreb',
                'primary_language_code' => 'hr',
            ],
            [
                'name'                 => 'Hungary',
                'code'                 => 'HU',
                'flag'                 => 'hu',
                'flag_emoji'           => '🇭🇺',
                'timezone'             => 'Europe/Budapest',
                'primary_language_code' => 'hu',
            ],
            [
                'name'                 => 'Ireland',
                'code'                 => 'IE',
                'flag'                 => 'ie',
                'flag_emoji'           => '🇮🇪',
                'timezone'             => 'Europe/Dublin',
                'primary_language_code' => 'en',
            ],
            [
                'name'                 => 'Iceland',
                'code'                 => 'IS',
                'flag'                 => 'is',
                'flag_emoji'           => '🇮🇸',
                'timezone'             => 'Atlantic/Reykjavik',
                'primary_language_code' => 'en',
            ],
            [
                'name'                 => 'Italy',
                'code'                 => 'IT',
                'flag'                 => 'it',
                'flag_emoji'           => '🇮🇹',
                'timezone'             => 'Europe/Rome',
                'primary_language_code' => 'it',
            ],
            [
                'name'                 => 'Liechtenstein',
                'code'                 => 'LI',
                'flag'                 => 'li',
                'flag_emoji'           => '🇱🇮',
                'timezone'             => 'Europe/Vaduz',
                'primary_language_code' => 'de',
            ],
            [
                'name'                 => 'Lithuania',
                'code'                 => 'LT',
                'flag'                 => 'lt',
                'flag_emoji'           => '🇱🇹',
                'timezone'             => 'Europe/Vilnius',
                'primary_language_code' => 'en',
            ],
            [
                'name'                 => 'Luxembourg',
                'code'                 => 'LU',
                'flag'                 => 'lu',
                'flag_emoji'           => '🇱🇺',
                'timezone'             => 'Europe/Luxembourg',
                'primary_language_code' => 'fr',
            ],
            [
                'name'                 => 'Latvia',
                'code'                 => 'LV',
                'flag'                 => 'lv',
                'flag_emoji'           => '🇱🇻',
                'timezone'             => 'Europe/Riga',
                'primary_language_code' => 'en',
            ],
            [
                'name'                 => 'Monaco',
                'code'                 => 'MC',
                'flag'                 => 'mc',
                'flag_emoji'           => '🇲🇨',
                'timezone'             => 'Europe/Monaco',
                'primary_language_code' => 'fr',
            ],
            [
                'name'                 => 'Moldova',
                'code'                 => 'MD',
                'flag'                 => 'md',
                'flag_emoji'           => '🇲🇩',
                'timezone'             => 'Europe/Chisinau',
                'primary_language_code' => 'ro',
            ],
            [
                'name'                 => 'Montenegro',
                'code'                 => 'ME',
                'flag'                 => 'me',
                'flag_emoji'           => '🇲🇪',
                'timezone'             => 'Europe/Podgorica',
                'primary_language_code' => 'sr',
            ],
            [
                'name'                 => 'North Macedonia',
                'code'                 => 'MK',
                'flag'                 => 'mk',
                'flag_emoji'           => '🇲🇰',
                'timezone'             => 'Europe/Skopje',
                'primary_language_code' => 'en',
            ],
            [
                'name'                 => 'Malta',
                'code'                 => 'MT',
                'flag'                 => 'mt',
                'flag_emoji'           => '🇲🇹',
                'timezone'             => 'Europe/Malta',
                'primary_language_code' => 'en',
            ],
            [
                'name'                 => 'Netherlands',
                'code'                 => 'NL',
                'flag'                 => 'nl',
                'flag_emoji'           => '🇳🇱',
                'timezone'             => 'Europe/Amsterdam',
                'primary_language_code' => 'nl',
            ],
            [
                'name'                 => 'Norway',
                'code'                 => 'NO',
                'flag'                 => 'no',
                'flag_emoji'           => '🇳🇴',
                'timezone'             => 'Europe/Oslo',
                'primary_language_code' => 'no',
            ],
            [
                'name'                 => 'Poland',
                'code'                 => 'PL',
                'flag'                 => 'pl',
                'flag_emoji'           => '🇵🇱',
                'timezone'             => 'Europe/Warsaw',
                'primary_language_code' => 'pl',
            ],
            [
                'name'                 => 'Portugal',
                'code'                 => 'PT',
                'flag'                 => 'pt',
                'flag_emoji'           => '🇵🇹',
                'timezone'             => 'Europe/Lisbon',
                'primary_language_code' => 'pt',
            ],
            [
                'name'                 => 'Romania',
                'code'                 => 'RO',
                'flag'                 => 'ro',
                'flag_emoji'           => '🇷🇴',
                'timezone'             => 'Europe/Bucharest',
                'primary_language_code' => 'ro',
            ],
            [
                'name'                 => 'Serbia',
                'code'                 => 'RS',
                'flag'                 => 'rs',
                'flag_emoji'           => '🇷🇸',
                'timezone'             => 'Europe/Belgrade',
                'primary_language_code' => 'sr',
            ],
            [
                'name'                 => 'Russia',
                'code'                 => 'RU',
                'flag'                 => 'ru',
                'flag_emoji'           => '🇷🇺',
                'timezone'             => 'Europe/Moscow',
                'primary_language_code' => 'ru',
            ],
            [
                'name'                 => 'Sweden',
                'code'                 => 'SE',
                'flag'                 => 'se',
                'flag_emoji'           => '🇸🇪',
                'timezone'             => 'Europe/Stockholm',
                'primary_language_code' => 'sv',
            ],
            [
                'name'                 => 'Slovenia',
                'code'                 => 'SI',
                'flag'                 => 'si',
                'flag_emoji'           => '🇸🇮',
                'timezone'             => 'Europe/Ljubljana',
                'primary_language_code' => 'en',
            ],
            [
                'name'                 => 'Slovakia',
                'code'                 => 'SK',
                'flag'                 => 'sk',
                'flag_emoji'           => '🇸🇰',
                'timezone'             => 'Europe/Bratislava',
                'primary_language_code' => 'cs',
            ],
            [
                'name'                 => 'San Marino',
                'code'                 => 'SM',
                'flag'                 => 'sm',
                'flag_emoji'           => '🇸🇲',
                'timezone'             => 'Europe/San_Marino',
                'primary_language_code' => 'it',
            ],
            [
                'name'                 => 'Turkey',
                'code'                 => 'TR',
                'flag'                 => 'tr',
                'flag_emoji'           => '🇹🇷',
                'timezone'             => 'Europe/Istanbul',
                'primary_language_code' => 'tr',
            ],
            [
                'name'                 => 'Ukraine',
                'code'                 => 'UA',
                'flag'                 => 'ua',
                'flag_emoji'           => '🇺🇦',
                'timezone'             => 'Europe/Kyiv',
                'primary_language_code' => 'uk',
            ],
            [
                'name'                 => 'Vatican City',
                'code'                 => 'VA',
                'flag'                 => 'va',
                'flag_emoji'           => '🇻🇦',
                'timezone'             => 'Europe/Vatican',
                'primary_language_code' => 'it',
            ],

            // ── Americas ─────────────────────────────────────────────────────
            [
                'name'                 => 'Antigua and Barbuda',
                'code'                 => 'AG',
                'flag'                 => 'ag',
                'flag_emoji'           => '🇦🇬',
                'timezone'             => 'America/Antigua',
                'primary_language_code' => 'en',
            ],
            [
                'name'                 => 'Argentina',
                'code'                 => 'AR',
                'flag'                 => 'ar',
                'flag_emoji'           => '🇦🇷',
                'timezone'             => 'America/Argentina/Buenos_Aires',
                'primary_language_code' => 'es',
            ],
            [
                'name'                 => 'Barbados',
                'code'                 => 'BB',
                'flag'                 => 'bb',
                'flag_emoji'           => '🇧🇧',
                'timezone'             => 'America/Barbados',
                'primary_language_code' => 'en',
            ],
            [
                'name'                 => 'Bolivia',
                'code'                 => 'BO',
                'flag'                 => 'bo',
                'flag_emoji'           => '🇧🇴',
                'timezone'             => 'America/La_Paz',
                'primary_language_code' => 'es',
            ],
            [
                'name'                 => 'Brazil',
                'code'                 => 'BR',
                'flag'                 => 'br',
                'flag_emoji'           => '🇧🇷',
                'timezone'             => 'America/Sao_Paulo',
                'primary_language_code' => 'pt',
            ],
            [
                'name'                 => 'Bahamas',
                'code'                 => 'BS',
                'flag'                 => 'bs',
                'flag_emoji'           => '🇧🇸',
                'timezone'             => 'America/Nassau',
                'primary_language_code' => 'en',
            ],
            [
                'name'                 => 'Belize',
                'code'                 => 'BZ',
                'flag'                 => 'bz',
                'flag_emoji'           => '🇧🇿',
                'timezone'             => 'America/Belize',
                'primary_language_code' => 'en',
            ],
            [
                'name'                 => 'Canada',
                'code'                 => 'CA',
                'flag'                 => 'ca',
                'flag_emoji'           => '🇨🇦',
                'timezone'             => 'America/Toronto',
                'primary_language_code' => 'en',
            ],
            [
                'name'                 => 'Chile',
                'code'                 => 'CL',
                'flag'                 => 'cl',
                'flag_emoji'           => '🇨🇱',
                'timezone'             => 'America/Santiago',
                'primary_language_code' => 'es',
            ],
            [
                'name'                 => 'Colombia',
                'code'                 => 'CO',
                'flag'                 => 'co',
                'flag_emoji'           => '🇨🇴',
                'timezone'             => 'America/Bogota',
                'primary_language_code' => 'es',
            ],
            [
                'name'                 => 'Costa Rica',
                'code'                 => 'CR',
                'flag'                 => 'cr',
                'flag_emoji'           => '🇨🇷',
                'timezone'             => 'America/Costa_Rica',
                'primary_language_code' => 'es',
            ],
            [
                'name'                 => 'Cuba',
                'code'                 => 'CU',
                'flag'                 => 'cu',
                'flag_emoji'           => '🇨🇺',
                'timezone'             => 'America/Havana',
                'primary_language_code' => 'es',
            ],
            [
                'name'                 => 'Dominica',
                'code'                 => 'DM',
                'flag'                 => 'dm',
                'flag_emoji'           => '🇩🇲',
                'timezone'             => 'America/Dominica',
                'primary_language_code' => 'en',
            ],
            [
                'name'                 => 'Dominican Republic',
                'code'                 => 'DO',
                'flag'                 => 'do',
                'flag_emoji'           => '🇩🇴',
                'timezone'             => 'America/Santo_Domingo',
                'primary_language_code' => 'es',
            ],
            [
                'name'                 => 'Ecuador',
                'code'                 => 'EC',
                'flag'                 => 'ec',
                'flag_emoji'           => '🇪🇨',
                'timezone'             => 'America/Guayaquil',
                'primary_language_code' => 'es',
            ],
            [
                'name'                 => 'Grenada',
                'code'                 => 'GD',
                'flag'                 => 'gd',
                'flag_emoji'           => '🇬🇩',
                'timezone'             => 'America/Grenada',
                'primary_language_code' => 'en',
            ],
            [
                'name'                 => 'Guatemala',
                'code'                 => 'GT',
                'flag'                 => 'gt',
                'flag_emoji'           => '🇬🇹',
                'timezone'             => 'America/Guatemala',
                'primary_language_code' => 'es',
            ],
            [
                'name'                 => 'Guyana',
                'code'                 => 'GY',
                'flag'                 => 'gy',
                'flag_emoji'           => '🇬🇾',
                'timezone'             => 'America/Guyana',
                'primary_language_code' => 'en',
            ],
            [
                'name'                 => 'Honduras',
                'code'                 => 'HN',
                'flag'                 => 'hn',
                'flag_emoji'           => '🇭🇳',
                'timezone'             => 'America/Tegucigalpa',
                'primary_language_code' => 'es',
            ],
            [
                'name'                 => 'Haiti',
                'code'                 => 'HT',
                'flag'                 => 'ht',
                'flag_emoji'           => '🇭🇹',
                'timezone'             => 'America/Port-au-Prince',
                'primary_language_code' => 'fr',
            ],
            [
                'name'                 => 'Jamaica',
                'code'                 => 'JM',
                'flag'                 => 'jm',
                'flag_emoji'           => '🇯🇲',
                'timezone'             => 'America/Jamaica',
                'primary_language_code' => 'en',
            ],
            [
                'name'                 => 'Saint Kitts and Nevis',
                'code'                 => 'KN',
                'flag'                 => 'kn',
                'flag_emoji'           => '🇰🇳',
                'timezone'             => 'America/St_Kitts',
                'primary_language_code' => 'en',
            ],
            [
                'name'                 => 'Saint Lucia',
                'code'                 => 'LC',
                'flag'                 => 'lc',
                'flag_emoji'           => '🇱🇨',
                'timezone'             => 'America/St_Lucia',
                'primary_language_code' => 'en',
            ],
            [
                'name'                 => 'Mexico',
                'code'                 => 'MX',
                'flag'                 => 'mx',
                'flag_emoji'           => '🇲🇽',
                'timezone'             => 'America/Mexico_City',
                'primary_language_code' => 'es',
            ],
            [
                'name'                 => 'Nicaragua',
                'code'                 => 'NI',
                'flag'                 => 'ni',
                'flag_emoji'           => '🇳🇮',
                'timezone'             => 'America/Managua',
                'primary_language_code' => 'es',
            ],
            [
                'name'                 => 'Panama',
                'code'                 => 'PA',
                'flag'                 => 'pa',
                'flag_emoji'           => '🇵🇦',
                'timezone'             => 'America/Panama',
                'primary_language_code' => 'es',
            ],
            [
                'name'                 => 'Peru',
                'code'                 => 'PE',
                'flag'                 => 'pe',
                'flag_emoji'           => '🇵🇪',
                'timezone'             => 'America/Lima',
                'primary_language_code' => 'es',
            ],
            [
                'name'                 => 'Paraguay',
                'code'                 => 'PY',
                'flag'                 => 'py',
                'flag_emoji'           => '🇵🇾',
                'timezone'             => 'America/Asuncion',
                'primary_language_code' => 'es',
            ],
            [
                'name'                 => 'Suriname',
                'code'                 => 'SR',
                'flag'                 => 'sr',
                'flag_emoji'           => '🇸🇷',
                'timezone'             => 'America/Paramaribo',
                'primary_language_code' => 'nl',
            ],
            [
                'name'                 => 'El Salvador',
                'code'                 => 'SV',
                'flag'                 => 'sv',
                'flag_emoji'           => '🇸🇻',
                'timezone'             => 'America/El_Salvador',
                'primary_language_code' => 'es',
            ],
            [
                'name'                 => 'Trinidad and Tobago',
                'code'                 => 'TT',
                'flag'                 => 'tt',
                'flag_emoji'           => '🇹🇹',
                'timezone'             => 'America/Port_of_Spain',
                'primary_language_code' => 'en',
            ],
            [
                'name'                 => 'United States',
                'code'                 => 'US',
                'flag'                 => 'us',
                'flag_emoji'           => '🇺🇸',
                'timezone'             => 'America/New_York',
                'primary_language_code' => 'en',
            ],
            [
                'name'                 => 'Uruguay',
                'code'                 => 'UY',
                'flag'                 => 'uy',
                'flag_emoji'           => '🇺🇾',
                'timezone'             => 'America/Montevideo',
                'primary_language_code' => 'es',
            ],
            [
                'name'                 => 'Saint Vincent and the Grenadines',
                'code'                 => 'VC',
                'flag'                 => 'vc',
                'flag_emoji'           => '🇻🇨',
                'timezone'             => 'America/St_Vincent',
                'primary_language_code' => 'en',
            ],
            [
                'name'                 => 'Venezuela',
                'code'                 => 'VE',
                'flag'                 => 've',
                'flag_emoji'           => '🇻🇪',
                'timezone'             => 'America/Caracas',
                'primary_language_code' => 'es',
            ],

            // ── Africa ───────────────────────────────────────────────────────
            [
                'name'                 => 'Angola',
                'code'                 => 'AO',
                'flag'                 => 'ao',
                'flag_emoji'           => '🇦🇴',
                'timezone'             => 'Africa/Luanda',
                'primary_language_code' => 'pt',
            ],
            [
                'name'                 => 'Burkina Faso',
                'code'                 => 'BF',
                'flag'                 => 'bf',
                'flag_emoji'           => '🇧🇫',
                'timezone'             => 'Africa/Ouagadougou',
                'primary_language_code' => 'fr',
            ],
            [
                'name'                 => 'Burundi',
                'code'                 => 'BI',
                'flag'                 => 'bi',
                'flag_emoji'           => '🇧🇮',
                'timezone'             => 'Africa/Bujumbura',
                'primary_language_code' => 'fr',
            ],
            [
                'name'                 => 'Benin',
                'code'                 => 'BJ',
                'flag'                 => 'bj',
                'flag_emoji'           => '🇧🇯',
                'timezone'             => 'Africa/Porto-Novo',
                'primary_language_code' => 'fr',
            ],
            [
                'name'                 => 'Botswana',
                'code'                 => 'BW',
                'flag'                 => 'bw',
                'flag_emoji'           => '🇧🇼',
                'timezone'             => 'Africa/Gaborone',
                'primary_language_code' => 'en',
            ],
            [
                'name'                 => 'DR Congo',
                'code'                 => 'CD',
                'flag'                 => 'cd',
                'flag_emoji'           => '🇨🇩',
                'timezone'             => 'Africa/Kinshasa',
                'primary_language_code' => 'fr',
            ],
            [
                'name'                 => 'Central African Republic',
                'code'                 => 'CF',
                'flag'                 => 'cf',
                'flag_emoji'           => '🇨🇫',
                'timezone'             => 'Africa/Bangui',
                'primary_language_code' => 'fr',
            ],
            [
                'name'                 => 'Republic of Congo',
                'code'                 => 'CG',
                'flag'                 => 'cg',
                'flag_emoji'           => '🇨🇬',
                'timezone'             => 'Africa/Brazzaville',
                'primary_language_code' => 'fr',
            ],
            [
                'name'                 => 'Ivory Coast',
                'code'                 => 'CI',
                'flag'                 => 'ci',
                'flag_emoji'           => '🇨🇮',
                'timezone'             => 'Africa/Abidjan',
                'primary_language_code' => 'fr',
            ],
            [
                'name'                 => 'Cameroon',
                'code'                 => 'CM',
                'flag'                 => 'cm',
                'flag_emoji'           => '🇨🇲',
                'timezone'             => 'Africa/Douala',
                'primary_language_code' => 'fr',
            ],
            [
                'name'                 => 'Cape Verde',
                'code'                 => 'CV',
                'flag'                 => 'cv',
                'flag_emoji'           => '🇨🇻',
                'timezone'             => 'Atlantic/Cape_Verde',
                'primary_language_code' => 'pt',
            ],
            [
                'name'                 => 'Djibouti',
                'code'                 => 'DJ',
                'flag'                 => 'dj',
                'flag_emoji'           => '🇩🇯',
                'timezone'             => 'Africa/Djibouti',
                'primary_language_code' => 'fr',
            ],
            [
                'name'                 => 'Algeria',
                'code'                 => 'DZ',
                'flag'                 => 'dz',
                'flag_emoji'           => '🇩🇿',
                'timezone'             => 'Africa/Algiers',
                'primary_language_code' => 'ar',
            ],
            [
                'name'                 => 'Egypt',
                'code'                 => 'EG',
                'flag'                 => 'eg',
                'flag_emoji'           => '🇪🇬',
                'timezone'             => 'Africa/Cairo',
                'primary_language_code' => 'ar',
            ],
            [
                'name'                 => 'Eritrea',
                'code'                 => 'ER',
                'flag'                 => 'er',
                'flag_emoji'           => '🇪🇷',
                'timezone'             => 'Africa/Asmara',
                'primary_language_code' => 'ar',
            ],
            [
                'name'                 => 'Ethiopia',
                'code'                 => 'ET',
                'flag'                 => 'et',
                'flag_emoji'           => '🇪🇹',
                'timezone'             => 'Africa/Addis_Ababa',
                'primary_language_code' => 'en',
            ],
            [
                'name'                 => 'Gabon',
                'code'                 => 'GA',
                'flag'                 => 'ga',
                'flag_emoji'           => '🇬🇦',
                'timezone'             => 'Africa/Libreville',
                'primary_language_code' => 'fr',
            ],
            [
                'name'                 => 'Ghana',
                'code'                 => 'GH',
                'flag'                 => 'gh',
                'flag_emoji'           => '🇬🇭',
                'timezone'             => 'Africa/Accra',
                'primary_language_code' => 'en',
            ],
            [
                'name'                 => 'Gambia',
                'code'                 => 'GM',
                'flag'                 => 'gm',
                'flag_emoji'           => '🇬🇲',
                'timezone'             => 'Africa/Banjul',
                'primary_language_code' => 'en',
            ],
            [
                'name'                 => 'Guinea',
                'code'                 => 'GN',
                'flag'                 => 'gn',
                'flag_emoji'           => '🇬🇳',
                'timezone'             => 'Africa/Conakry',
                'primary_language_code' => 'fr',
            ],
            [
                'name'                 => 'Equatorial Guinea',
                'code'                 => 'GQ',
                'flag'                 => 'gq',
                'flag_emoji'           => '🇬🇶',
                'timezone'             => 'Africa/Malabo',
                'primary_language_code' => 'es',
            ],
            [
                'name'                 => 'Guinea-Bissau',
                'code'                 => 'GW',
                'flag'                 => 'gw',
                'flag_emoji'           => '🇬🇼',
                'timezone'             => 'Africa/Bissau',
                'primary_language_code' => 'pt',
            ],
            [
                'name'                 => 'Kenya',
                'code'                 => 'KE',
                'flag'                 => 'ke',
                'flag_emoji'           => '🇰🇪',
                'timezone'             => 'Africa/Nairobi',
                'primary_language_code' => 'en',
            ],
            [
                'name'                 => 'Comoros',
                'code'                 => 'KM',
                'flag'                 => 'km',
                'flag_emoji'           => '🇰🇲',
                'timezone'             => 'Indian/Comoro',
                'primary_language_code' => 'ar',
            ],
            [
                'name'                 => 'Liberia',
                'code'                 => 'LR',
                'flag'                 => 'lr',
                'flag_emoji'           => '🇱🇷',
                'timezone'             => 'Africa/Monrovia',
                'primary_language_code' => 'en',
            ],
            [
                'name'                 => 'Lesotho',
                'code'                 => 'LS',
                'flag'                 => 'ls',
                'flag_emoji'           => '🇱🇸',
                'timezone'             => 'Africa/Maseru',
                'primary_language_code' => 'en',
            ],
            [
                'name'                 => 'Libya',
                'code'                 => 'LY',
                'flag'                 => 'ly',
                'flag_emoji'           => '🇱🇾',
                'timezone'             => 'Africa/Tripoli',
                'primary_language_code' => 'ar',
            ],
            [
                'name'                 => 'Morocco',
                'code'                 => 'MA',
                'flag'                 => 'ma',
                'flag_emoji'           => '🇲🇦',
                'timezone'             => 'Africa/Casablanca',
                'primary_language_code' => 'ar',
            ],
            [
                'name'                 => 'Madagascar',
                'code'                 => 'MG',
                'flag'                 => 'mg',
                'flag_emoji'           => '🇲🇬',
                'timezone'             => 'Indian/Antananarivo',
                'primary_language_code' => 'fr',
            ],
            [
                'name'                 => 'Mali',
                'code'                 => 'ML',
                'flag'                 => 'ml',
                'flag_emoji'           => '🇲🇱',
                'timezone'             => 'Africa/Bamako',
                'primary_language_code' => 'fr',
            ],
            [
                'name'                 => 'Mauritania',
                'code'                 => 'MR',
                'flag'                 => 'mr',
                'flag_emoji'           => '🇲🇷',
                'timezone'             => 'Africa/Nouakchott',
                'primary_language_code' => 'ar',
            ],
            [
                'name'                 => 'Mauritius',
                'code'                 => 'MU',
                'flag'                 => 'mu',
                'flag_emoji'           => '🇲🇺',
                'timezone'             => 'Indian/Mauritius',
                'primary_language_code' => 'en',
            ],
            [
                'name'                 => 'Malawi',
                'code'                 => 'MW',
                'flag'                 => 'mw',
                'flag_emoji'           => '🇲🇼',
                'timezone'             => 'Africa/Blantyre',
                'primary_language_code' => 'en',
            ],
            [
                'name'                 => 'Mozambique',
                'code'                 => 'MZ',
                'flag'                 => 'mz',
                'flag_emoji'           => '🇲🇿',
                'timezone'             => 'Africa/Maputo',
                'primary_language_code' => 'pt',
            ],
            [
                'name'                 => 'Namibia',
                'code'                 => 'NA',
                'flag'                 => 'na',
                'flag_emoji'           => '🇳🇦',
                'timezone'             => 'Africa/Windhoek',
                'primary_language_code' => 'en',
            ],
            [
                'name'                 => 'Niger',
                'code'                 => 'NE',
                'flag'                 => 'ne',
                'flag_emoji'           => '🇳🇪',
                'timezone'             => 'Africa/Niamey',
                'primary_language_code' => 'fr',
            ],
            [
                'name'                 => 'Nigeria',
                'code'                 => 'NG',
                'flag'                 => 'ng',
                'flag_emoji'           => '🇳🇬',
                'timezone'             => 'Africa/Lagos',
                'primary_language_code' => 'en',
            ],
            [
                'name'                 => 'Rwanda',
                'code'                 => 'RW',
                'flag'                 => 'rw',
                'flag_emoji'           => '🇷🇼',
                'timezone'             => 'Africa/Kigali',
                'primary_language_code' => 'en',
            ],
            [
                'name'                 => 'Seychelles',
                'code'                 => 'SC',
                'flag'                 => 'sc',
                'flag_emoji'           => '🇸🇨',
                'timezone'             => 'Indian/Mahe',
                'primary_language_code' => 'fr',
            ],
            [
                'name'                 => 'Sudan',
                'code'                 => 'SD',
                'flag'                 => 'sd',
                'flag_emoji'           => '🇸🇩',
                'timezone'             => 'Africa/Khartoum',
                'primary_language_code' => 'ar',
            ],
            [
                'name'                 => 'Sierra Leone',
                'code'                 => 'SL',
                'flag'                 => 'sl',
                'flag_emoji'           => '🇸🇱',
                'timezone'             => 'Africa/Freetown',
                'primary_language_code' => 'en',
            ],
            [
                'name'                 => 'Senegal',
                'code'                 => 'SN',
                'flag'                 => 'sn',
                'flag_emoji'           => '🇸🇳',
                'timezone'             => 'Africa/Dakar',
                'primary_language_code' => 'fr',
            ],
            [
                'name'                 => 'Somalia',
                'code'                 => 'SO',
                'flag'                 => 'so',
                'flag_emoji'           => '🇸🇴',
                'timezone'             => 'Africa/Mogadishu',
                'primary_language_code' => 'ar',
            ],
            [
                'name'                 => 'South Sudan',
                'code'                 => 'SS',
                'flag'                 => 'ss',
                'flag_emoji'           => '🇸🇸',
                'timezone'             => 'Africa/Juba',
                'primary_language_code' => 'en',
            ],
            [
                'name'                 => 'São Tomé and Príncipe',
                'code'                 => 'ST',
                'flag'                 => 'st',
                'flag_emoji'           => '🇸🇹',
                'timezone'             => 'Africa/Sao_Tome',
                'primary_language_code' => 'pt',
            ],
            [
                'name'                 => 'Eswatini',
                'code'                 => 'SZ',
                'flag'                 => 'sz',
                'flag_emoji'           => '🇸🇿',
                'timezone'             => 'Africa/Mbabane',
                'primary_language_code' => 'en',
            ],
            [
                'name'                 => 'Chad',
                'code'                 => 'TD',
                'flag'                 => 'td',
                'flag_emoji'           => '🇹🇩',
                'timezone'             => 'Africa/Ndjamena',
                'primary_language_code' => 'fr',
            ],
            [
                'name'                 => 'Togo',
                'code'                 => 'TG',
                'flag'                 => 'tg',
                'flag_emoji'           => '🇹🇬',
                'timezone'             => 'Africa/Lome',
                'primary_language_code' => 'fr',
            ],
            [
                'name'                 => 'Tunisia',
                'code'                 => 'TN',
                'flag'                 => 'tn',
                'flag_emoji'           => '🇹🇳',
                'timezone'             => 'Africa/Tunis',
                'primary_language_code' => 'ar',
            ],
            [
                'name'                 => 'Tanzania',
                'code'                 => 'TZ',
                'flag'                 => 'tz',
                'flag_emoji'           => '🇹🇿',
                'timezone'             => 'Africa/Dar_es_Salaam',
                'primary_language_code' => 'en',
            ],
            [
                'name'                 => 'Uganda',
                'code'                 => 'UG',
                'flag'                 => 'ug',
                'flag_emoji'           => '🇺🇬',
                'timezone'             => 'Africa/Kampala',
                'primary_language_code' => 'en',
            ],
            [
                'name'                 => 'South Africa',
                'code'                 => 'ZA',
                'flag'                 => 'za',
                'flag_emoji'           => '🇿🇦',
                'timezone'             => 'Africa/Johannesburg',
                'primary_language_code' => 'en',
            ],
            [
                'name'                 => 'Zambia',
                'code'                 => 'ZM',
                'flag'                 => 'zm',
                'flag_emoji'           => '🇿🇲',
                'timezone'             => 'Africa/Lusaka',
                'primary_language_code' => 'en',
            ],
            [
                'name'                 => 'Zimbabwe',
                'code'                 => 'ZW',
                'flag'                 => 'zw',
                'flag_emoji'           => '🇿🇼',
                'timezone'             => 'Africa/Harare',
                'primary_language_code' => 'en',
            ],

            // ── Middle East ──────────────────────────────────────────────────
            [
                'name'                 => 'United Arab Emirates',
                'code'                 => 'AE',
                'flag'                 => 'ae',
                'flag_emoji'           => '🇦🇪',
                'timezone'             => 'Asia/Dubai',
                'primary_language_code' => 'ar',
            ],
            [
                'name'                 => 'Bahrain',
                'code'                 => 'BH',
                'flag'                 => 'bh',
                'flag_emoji'           => '🇧🇭',
                'timezone'             => 'Asia/Bahrain',
                'primary_language_code' => 'ar',
            ],
            [
                'name'                 => 'Israel',
                'code'                 => 'IL',
                'flag'                 => 'il',
                'flag_emoji'           => '🇮🇱',
                'timezone'             => 'Asia/Jerusalem',
                'primary_language_code' => 'he',
            ],
            [
                'name'                 => 'Iraq',
                'code'                 => 'IQ',
                'flag'                 => 'iq',
                'flag_emoji'           => '🇮🇶',
                'timezone'             => 'Asia/Baghdad',
                'primary_language_code' => 'ar',
            ],
            [
                'name'                 => 'Iran',
                'code'                 => 'IR',
                'flag'                 => 'ir',
                'flag_emoji'           => '🇮🇷',
                'timezone'             => 'Asia/Tehran',
                'primary_language_code' => 'fa',
            ],
            [
                'name'                 => 'Jordan',
                'code'                 => 'JO',
                'flag'                 => 'jo',
                'flag_emoji'           => '🇯🇴',
                'timezone'             => 'Asia/Amman',
                'primary_language_code' => 'ar',
            ],
            [
                'name'                 => 'Kuwait',
                'code'                 => 'KW',
                'flag'                 => 'kw',
                'flag_emoji'           => '🇰🇼',
                'timezone'             => 'Asia/Kuwait',
                'primary_language_code' => 'ar',
            ],
            [
                'name'                 => 'Lebanon',
                'code'                 => 'LB',
                'flag'                 => 'lb',
                'flag_emoji'           => '🇱🇧',
                'timezone'             => 'Asia/Beirut',
                'primary_language_code' => 'ar',
            ],
            [
                'name'                 => 'Oman',
                'code'                 => 'OM',
                'flag'                 => 'om',
                'flag_emoji'           => '🇴🇲',
                'timezone'             => 'Asia/Muscat',
                'primary_language_code' => 'ar',
            ],
            [
                'name'                 => 'Palestine',
                'code'                 => 'PS',
                'flag'                 => 'ps',
                'flag_emoji'           => '🇵🇸',
                'timezone'             => 'Asia/Gaza',
                'primary_language_code' => 'ar',
            ],
            [
                'name'                 => 'Qatar',
                'code'                 => 'QA',
                'flag'                 => 'qa',
                'flag_emoji'           => '🇶🇦',
                'timezone'             => 'Asia/Qatar',
                'primary_language_code' => 'ar',
            ],
            [
                'name'                 => 'Saudi Arabia',
                'code'                 => 'SA',
                'flag'                 => 'sa',
                'flag_emoji'           => '🇸🇦',
                'timezone'             => 'Asia/Riyadh',
                'primary_language_code' => 'ar',
            ],
            [
                'name'                 => 'Syria',
                'code'                 => 'SY',
                'flag'                 => 'sy',
                'flag_emoji'           => '🇸🇾',
                'timezone'             => 'Asia/Damascus',
                'primary_language_code' => 'ar',
            ],
            [
                'name'                 => 'Yemen',
                'code'                 => 'YE',
                'flag'                 => 'ye',
                'flag_emoji'           => '🇾🇪',
                'timezone'             => 'Asia/Aden',
                'primary_language_code' => 'ar',
            ],

            // ── Asia & Oceania ────────────────────────────────────────────────
            [
                'name'                 => 'Afghanistan',
                'code'                 => 'AF',
                'flag'                 => 'af',
                'flag_emoji'           => '🇦🇫',
                'timezone'             => 'Asia/Kabul',
                'primary_language_code' => 'fa',
            ],
            [
                'name'                 => 'Armenia',
                'code'                 => 'AM',
                'flag'                 => 'am',
                'flag_emoji'           => '🇦🇲',
                'timezone'             => 'Asia/Yerevan',
                'primary_language_code' => 'en',
            ],
            [
                'name'                 => 'Australia',
                'code'                 => 'AU',
                'flag'                 => 'au',
                'flag_emoji'           => '🇦🇺',
                'timezone'             => 'Australia/Sydney',
                'primary_language_code' => 'en',
            ],
            [
                'name'                 => 'Azerbaijan',
                'code'                 => 'AZ',
                'flag'                 => 'az',
                'flag_emoji'           => '🇦🇿',
                'timezone'             => 'Asia/Baku',
                'primary_language_code' => 'en',
            ],
            [
                'name'                 => 'Bangladesh',
                'code'                 => 'BD',
                'flag'                 => 'bd',
                'flag_emoji'           => '🇧🇩',
                'timezone'             => 'Asia/Dhaka',
                'primary_language_code' => 'bn',
            ],
            [
                'name'                 => 'Bhutan',
                'code'                 => 'BT',
                'flag'                 => 'bt',
                'flag_emoji'           => '🇧🇹',
                'timezone'             => 'Asia/Thimphu',
                'primary_language_code' => 'en',
            ],
            [
                'name'                 => 'Brunei',
                'code'                 => 'BN',
                'flag'                 => 'bn',
                'flag_emoji'           => '🇧🇳',
                'timezone'             => 'Asia/Brunei',
                'primary_language_code' => 'ms',
            ],
            [
                'name'                 => 'China',
                'code'                 => 'CN',
                'flag'                 => 'cn',
                'flag_emoji'           => '🇨🇳',
                'timezone'             => 'Asia/Shanghai',
                'primary_language_code' => 'zh',
            ],
            [
                'name'                 => 'Fiji',
                'code'                 => 'FJ',
                'flag'                 => 'fj',
                'flag_emoji'           => '🇫🇯',
                'timezone'             => 'Pacific/Fiji',
                'primary_language_code' => 'en',
            ],
            [
                'name'                 => 'Micronesia',
                'code'                 => 'FM',
                'flag'                 => 'fm',
                'flag_emoji'           => '🇫🇲',
                'timezone'             => 'Pacific/Pohnpei',
                'primary_language_code' => 'en',
            ],
            [
                'name'                 => 'Georgia',
                'code'                 => 'GE',
                'flag'                 => 'ge',
                'flag_emoji'           => '🇬🇪',
                'timezone'             => 'Asia/Tbilisi',
                'primary_language_code' => 'en',
            ],
            [
                'name'                 => 'Indonesia',
                'code'                 => 'ID',
                'flag'                 => 'id',
                'flag_emoji'           => '🇮🇩',
                'timezone'             => 'Asia/Jakarta',
                'primary_language_code' => 'id',
            ],
            [
                'name'                 => 'India',
                'code'                 => 'IN',
                'flag'                 => 'in',
                'flag_emoji'           => '🇮🇳',
                'timezone'             => 'Asia/Kolkata',
                'primary_language_code' => 'hi',
            ],
            [
                'name'                 => 'Japan',
                'code'                 => 'JP',
                'flag'                 => 'jp',
                'flag_emoji'           => '🇯🇵',
                'timezone'             => 'Asia/Tokyo',
                'primary_language_code' => 'ja',
            ],
            [
                'name'                 => 'Kyrgyzstan',
                'code'                 => 'KG',
                'flag'                 => 'kg',
                'flag_emoji'           => '🇰🇬',
                'timezone'             => 'Asia/Bishkek',
                'primary_language_code' => 'ru',
            ],
            [
                'name'                 => 'Cambodia',
                'code'                 => 'KH',
                'flag'                 => 'kh',
                'flag_emoji'           => '🇰🇭',
                'timezone'             => 'Asia/Phnom_Penh',
                'primary_language_code' => 'en',
            ],
            [
                'name'                 => 'Kiribati',
                'code'                 => 'KI',
                'flag'                 => 'ki',
                'flag_emoji'           => '🇰🇮',
                'timezone'             => 'Pacific/Tarawa',
                'primary_language_code' => 'en',
            ],
            [
                'name'                 => 'North Korea',
                'code'                 => 'KP',
                'flag'                 => 'kp',
                'flag_emoji'           => '🇰🇵',
                'timezone'             => 'Asia/Pyongyang',
                'primary_language_code' => 'ko',
            ],
            [
                'name'                 => 'South Korea',
                'code'                 => 'KR',
                'flag'                 => 'kr',
                'flag_emoji'           => '🇰🇷',
                'timezone'             => 'Asia/Seoul',
                'primary_language_code' => 'ko',
            ],
            [
                'name'                 => 'Kazakhstan',
                'code'                 => 'KZ',
                'flag'                 => 'kz',
                'flag_emoji'           => '🇰🇿',
                'timezone'             => 'Asia/Almaty',
                'primary_language_code' => 'ru',
            ],
            [
                'name'                 => 'Laos',
                'code'                 => 'LA',
                'flag'                 => 'la',
                'flag_emoji'           => '🇱🇦',
                'timezone'             => 'Asia/Vientiane',
                'primary_language_code' => 'en',
            ],
            [
                'name'                 => 'Sri Lanka',
                'code'                 => 'LK',
                'flag'                 => 'lk',
                'flag_emoji'           => '🇱🇰',
                'timezone'             => 'Asia/Colombo',
                'primary_language_code' => 'en',
            ],
            [
                'name'                 => 'Marshall Islands',
                'code'                 => 'MH',
                'flag'                 => 'mh',
                'flag_emoji'           => '🇲🇭',
                'timezone'             => 'Pacific/Majuro',
                'primary_language_code' => 'en',
            ],
            [
                'name'                 => 'Myanmar',
                'code'                 => 'MM',
                'flag'                 => 'mm',
                'flag_emoji'           => '🇲🇲',
                'timezone'             => 'Asia/Yangon',
                'primary_language_code' => 'en',
            ],
            [
                'name'                 => 'Mongolia',
                'code'                 => 'MN',
                'flag'                 => 'mn',
                'flag_emoji'           => '🇲🇳',
                'timezone'             => 'Asia/Ulaanbaatar',
                'primary_language_code' => 'en',
            ],
            [
                'name'                 => 'Maldives',
                'code'                 => 'MV',
                'flag'                 => 'mv',
                'flag_emoji'           => '🇲🇻',
                'timezone'             => 'Indian/Maldives',
                'primary_language_code' => 'en',
            ],
            [
                'name'                 => 'Malaysia',
                'code'                 => 'MY',
                'flag'                 => 'my',
                'flag_emoji'           => '🇲🇾',
                'timezone'             => 'Asia/Kuala_Lumpur',
                'primary_language_code' => 'ms',
            ],
            [
                'name'                 => 'Nauru',
                'code'                 => 'NR',
                'flag'                 => 'nr',
                'flag_emoji'           => '🇳🇷',
                'timezone'             => 'Pacific/Nauru',
                'primary_language_code' => 'en',
            ],
            [
                'name'                 => 'Nepal',
                'code'                 => 'NP',
                'flag'                 => 'np',
                'flag_emoji'           => '🇳🇵',
                'timezone'             => 'Asia/Kathmandu',
                'primary_language_code' => 'en',
            ],
            [
                'name'                 => 'New Zealand',
                'code'                 => 'NZ',
                'flag'                 => 'nz',
                'flag_emoji'           => '🇳🇿',
                'timezone'             => 'Pacific/Auckland',
                'primary_language_code' => 'en',
            ],
            [
                'name'                 => 'Philippines',
                'code'                 => 'PH',
                'flag'                 => 'ph',
                'flag_emoji'           => '🇵🇭',
                'timezone'             => 'Asia/Manila',
                'primary_language_code' => 'tl',
            ],
            [
                'name'                 => 'Pakistan',
                'code'                 => 'PK',
                'flag'                 => 'pk',
                'flag_emoji'           => '🇵🇰',
                'timezone'             => 'Asia/Karachi',
                'primary_language_code' => 'ur',
            ],
            [
                'name'                 => 'Papua New Guinea',
                'code'                 => 'PG',
                'flag'                 => 'pg',
                'flag_emoji'           => '🇵🇬',
                'timezone'             => 'Pacific/Port_Moresby',
                'primary_language_code' => 'en',
            ],
            [
                'name'                 => 'Palau',
                'code'                 => 'PW',
                'flag'                 => 'pw',
                'flag_emoji'           => '🇵🇼',
                'timezone'             => 'Pacific/Palau',
                'primary_language_code' => 'en',
            ],
            [
                'name'                 => 'Singapore',
                'code'                 => 'SG',
                'flag'                 => 'sg',
                'flag_emoji'           => '🇸🇬',
                'timezone'             => 'Asia/Singapore',
                'primary_language_code' => 'ms',
            ],
            [
                'name'                 => 'Solomon Islands',
                'code'                 => 'SB',
                'flag'                 => 'sb',
                'flag_emoji'           => '🇸🇧',
                'timezone'             => 'Pacific/Guadalcanal',
                'primary_language_code' => 'en',
            ],
            [
                'name'                 => 'Tajikistan',
                'code'                 => 'TJ',
                'flag'                 => 'tj',
                'flag_emoji'           => '🇹🇯',
                'timezone'             => 'Asia/Dushanbe',
                'primary_language_code' => 'ru',
            ],
            [
                'name'                 => 'Timor-Leste',
                'code'                 => 'TL',
                'flag'                 => 'tl',
                'flag_emoji'           => '🇹🇱',
                'timezone'             => 'Asia/Dili',
                'primary_language_code' => 'pt',
            ],
            [
                'name'                 => 'Turkmenistan',
                'code'                 => 'TM',
                'flag'                 => 'tm',
                'flag_emoji'           => '🇹🇲',
                'timezone'             => 'Asia/Ashgabat',
                'primary_language_code' => 'ru',
            ],
            [
                'name'                 => 'Tonga',
                'code'                 => 'TO',
                'flag'                 => 'to',
                'flag_emoji'           => '🇹🇴',
                'timezone'             => 'Pacific/Tongatapu',
                'primary_language_code' => 'en',
            ],
            [
                'name'                 => 'Tuvalu',
                'code'                 => 'TV',
                'flag'                 => 'tv',
                'flag_emoji'           => '🇹🇻',
                'timezone'             => 'Pacific/Funafuti',
                'primary_language_code' => 'en',
            ],
            [
                'name'                 => 'Taiwan',
                'code'                 => 'TW',
                'flag'                 => 'tw',
                'flag_emoji'           => '🇹🇼',
                'timezone'             => 'Asia/Taipei',
                'primary_language_code' => 'zh',
            ],
            [
                'name'                 => 'Thailand',
                'code'                 => 'TH',
                'flag'                 => 'th',
                'flag_emoji'           => '🇹🇭',
                'timezone'             => 'Asia/Bangkok',
                'primary_language_code' => 'th',
            ],
            [
                'name'                 => 'Uzbekistan',
                'code'                 => 'UZ',
                'flag'                 => 'uz',
                'flag_emoji'           => '🇺🇿',
                'timezone'             => 'Asia/Tashkent',
                'primary_language_code' => 'ru',
            ],
            [
                'name'                 => 'Vanuatu',
                'code'                 => 'VU',
                'flag'                 => 'vu',
                'flag_emoji'           => '🇻🇺',
                'timezone'             => 'Pacific/Efate',
                'primary_language_code' => 'fr',
            ],
            [
                'name'                 => 'Vietnam',
                'code'                 => 'VN',
                'flag'                 => 'vn',
                'flag_emoji'           => '🇻🇳',
                'timezone'             => 'Asia/Ho_Chi_Minh',
                'primary_language_code' => 'vi',
            ],
            [
                'name'                 => 'Samoa',
                'code'                 => 'WS',
                'flag'                 => 'ws',
                'flag_emoji'           => '🇼🇸',
                'timezone'             => 'Pacific/Apia',
                'primary_language_code' => 'en',
            ],
        ];

        collect($countries)->each(function (array $data) use ($languageIds, $callingCodes)
        {
            $primaryCode = $data['primary_language_code'];
            unset($data['primary_language_code']);

            $data['primary_language_id'] = $languageIds[$primaryCode] ?? null;
            $data['calling_code']        = $callingCodes[$data['code']] ?? null;

            Country::updateOrCreate(['code' => $data['code']], $data);
        });
    }
}
